<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Label="Code quality">
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors></WarningsNotAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;CA1062;CA1848;CA1873;CA2007;CA1515;CA2227;CA1002;CA1716;CA1711</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="Build determinism and runtime">
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableRequestDelegateGenerator>false</EnableRequestDelegateGenerator>
  </PropertyGroup>

  <PropertyGroup Label="Packaging metadata">
    <Company>OFA-TECH</Company>
    <Authors>OFA-TECH</Authors>
    <Product>WebApi Project Template</Product>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1707;CA2234;CA1861;IDE0005</NoWarn>
  </PropertyGroup>

</Project>
