<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Data.GrpcApi</RootNamespace>
    <AssemblyName>Data.GrpcApi</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\**\*.proto" Exclude="Protos\greeter.proto" GrpcServices="Client" />
    <Protobuf Include="Protos\greeter.proto" GrpcServices="Both" />
  </ItemGroup>

</Project>
