<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Data.GraphqlApi</RootNamespace>
    <AssemblyName>Data.GraphqlApi</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GraphQL.Client" />
    <PackageReference Include="GraphQL.Client.Serializer.SystemTextJson" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

</Project>
