<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\WebApi\WebApi.csproj" />
    <ProjectReference Include="..\..\Source\Infrastructure\Data\Data.Sql\Data.Sql.csproj" />
    <ProjectReference Include="..\..\Source\Infrastructure\Data\Data.NoSql\Data.NoSql.csproj" />
    <ProjectReference Include="..\..\Source\Infrastructure\Api\Data.GrpcApi\Data.GrpcApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers.MongoDb" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>

</Project>
