<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.InMemory" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="Hangfire.SqlServer" />
    <PackageReference Include="Hangfire.Mongo" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Hangfire.Console.Extensions" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Hangfire" />
  </ItemGroup>

</Project>